// Main college website components index
export { Header } from "./layout/header.jsx";
export { HeroSection } from "./sections/home/hero-section.jsx";
export { StatsBar } from "./sections/home/stats-bar.jsx";
export { AboutSection } from "./sections/home/about-section.jsx";
export { CollegeOverviewSection } from "./sections/about/college-overview-section.jsx";
export { WhyChooseUsSection } from "./sections/home/why-choose-us-section.jsx";
export { PlacementsSection } from "./sections/home/placements-section.jsx";
export { TestimonialsSection } from "./sections/home/testimonials-section.jsx";
export { CTASection } from "./sections/home/cta-section.jsx";
export { MapSection } from "./sections/home/map-section.jsx";
export { Footer } from "./sections/home/footer.jsx";
export { CoursesSection } from "./sections/home/courses-section.jsx";
